site_name: AAM's Documentations
site_description: LTE Capacity Dimensioning, LTE Documentation, Capacity Calculation, LTE Calculator
site_author: Ali Asgher Mansoor Habiby
google_analytics: ['UA-57266485-4', 'https://aliasgherman.github.io/documentations']
nav:
    - Introduction: 'docs/index.md'
    - 'LTE Capacity Dimensioning': 'ltefdddimensioning.md'
    - 'LTE Capacity Calculator': 'ltefdd-capacitycalculator.md'
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
